version: '3'

services: 
  app: 
    build: .
    ports: 
      - "80:8000"
    depends_on: 
      - "postgres"

  postgres: 
    image: postgres:12
    environment: 
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - '5423:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
